site_name: ANGEL-PALMS HOME HEALTH CARE
site_url: http://angelpalmshhcare.com/
site_description: APHHC Documentation
theme:
  name: readthedocs
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/sosotechnologies/angel-hhc

markdown_extensions:
- markdown.extensions.admonition
nav:
 - Home: index.md
 - Homecare Services: 
   - Assisted Living: aphhc/services/assisted.md
  # - Critical Care: aphhc/services/critical.md
   - Hospice: aphhc/services/hospice.md
   - Palliative Care: aphhc/services/palliative.md
   - Pedriatic Care: aphhc/services/pedriatic.md
  # - Short Term Care: aphhc/services/short.md
   - Skilled Nursing: aphhc/services/skilled.md
 - Contacts: 
   - Contacts: aphhc/contacts/contacts.md
  
 
 
    